#     Data Analytics

## **Project 1**

**Project**: Data Cleaning & Preparation

**Dataset Name**: Dataset for Data Analytics.xlsx

About : E_Commerce Dataset

**Objective**:
Clean and prepare the raw dataset for further analysis.

**IMPORT LIBRARIES**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

**Load dataset**

In [ ]:
df=pd.read_excel("/content/Dataset for Data Analytics.xlsx")

**Understand dataset**

**Printing first 5 rows**

In [ ]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

**Number of rows and columns present in dataset**

In [ ]:
df.shape

(1200, 14)

In [ ]:
print("Number of rows : 1200")
print("Number of columns : 14")

Number of rows : 1200
Number of columns : 14

**Check missing values**

In [ ]:
print(f"Number of missing values in each column :\n")
df.isnull().sum()

Number of missing values in each column :

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
print(f"CouponCode has : '309' missing values\nRemaining columns has no missing values")

CouponCode has : '309' missing values
Remaining columns has no missing values

**Handling missing values and checking missing values after cleaning**

In [ ]:
print("Filling missing CouponCode with No_CouponCode")
df['CouponCode'] = df['CouponCode'].fillna('No_CouponCode')

print("Missing values after cleaning:")
print(df.isnull().sum())

Filling missing CouponCode with No_CouponCode
Missing values after cleaning:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

**Total missing values present in dataset**

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
print("No missing values are present.")

No missing values are present.

**Checking duplicates**

In [ ]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

**Duplicate IDs**

In [ ]:
print("Duplicate OrderIDs:", df["OrderID"].duplicated().sum())

Duplicate OrderIDs: 0

**Checking data types of each columns**

In [ ]:
print("Data types of each columns : ")
df.dtypes

Data types of each columns :

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

**How many corrupted dates were found**

In [ ]:
print("Invalid dates found:", df['Date'].isna().sum())

Invalid dates found: 0

**Text cleaning**

In [ ]:
df["Product"]=df["Product"].str.strip()

**Final validation**

In [ ]:
print("FINAL DATA VALIDATION")
print("----------------------")

print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("Duplicate OrderIDs:", df["OrderID"].duplicated().sum())

print("Invalid dates:", df["Date"].isna().sum())

print("\nData types:")
print(df.dtypes)

FINAL DATA VALIDATION
----------------------
Missing values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

Duplicate rows: 0
Duplicate OrderIDs: 0
Invalid dates: 0

Data types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

**Data Overview**

In [ ]:
print(f" Information about RangeIndex(rows), Columns , Column_name , Datatype of each column \n")
df.info()

 Information about RangeIndex(rows), Columns , Column_name , Datatype of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

**Statistical description about numerical data**

In [ ]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

**Statistical description about text data**

In [ ]:
print(f"count : Number of non missing rows \n")
print(f"unique: The number of distinct categories in that column.\n")
print(f"top: The most frequently occurring value in that column. \n")
print(f"freq: How many times that specific top value appears. \n")
df.describe(include="object")

count : Number of non missing rows

unique: The number of distinct categories in that column.

top: The most frequently occurring value in that column.

freq: How many times that specific top value appears.

,OrderID,CustomerID,Product,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,CouponCode,ReferralSource
count,1200,1200,1200,1200,1200,1200,1200,1200,1200
unique,1200,1189,7,655,5,5,1200,4,5
top,ORD201183,C46651,Printer,533 Main St,Online,Cancelled,TRK83653396,FREESHIP,Instagram
freq,1,2,181,8,258,250,1,313,259

**Data Cleaning Summary**

1. Identified missing values in the dataset.
2. Filled missing CouponCode values with "No_CouponCode".
3. Checked for duplicate rows; no duplicates were found.
4. Checked OrderID uniqueness; no duplicate OrderIDs were found.
5. Converted the Date column to datetime format.
6. Verified that there are no invalid dates.
7. Removed unnecessary whitespace from Product values.
8. Performed final validation to confirm the dataset is clean and ready for analysis.